services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_USER: demo
  #     POSTGRES_PASSWORD: demo
  #     POSTGRES_DB: analytics
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20
  #   restart: unless-stopped

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: backend-python
    env_file:
      - ./backend-python/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python/src:/app/src
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    restart: unless-stopped

  frontend-javascript:
    build:
      context: .
      dockerfile: ./frontend-javascript/Dockerfile
    container_name: frontend-javascript
    ports:
      - "3000:80"
    depends_on:
      - backend-python
    restart: unless-stopped
