from enum import Enum

from app.langgraph.stages import (
    STAGE_ASSISTANT_READY,
    STAGE_CHART_INTENT_REUSED,
    STAGE_CHART_REUSED,
    STAGE_CHART_INTENT_READY,
    STAGE_CHART_READY,
    STAGE_CORRECTING,
    STAGE_GENERATING,
    STAGE_INTENT_CLASSIFIED,
    STAGE_PLANNING,
    STAGE_PLANNING_DONE,
    STAGE_PROMPT_CACHE_HIT,
    STAGE_QUERY_EXECUTED,
    STAGE_REUSED_PREVIOUS_RESULT,
    STAGE_SQL_GENERATED,
    STAGE_SEARCHING,
    STAGE_SEARCHING_DONE,
)


class AskStatus(str, Enum):
    UNDERSTANDING = "understanding"
    SEARCHING = "searching"
    PLANNING = "planning"
    GENERATING = "generating"
    CORRECTING = "correcting"
    QUERY_EXECUTED = "query_executed"
    REUSED_PREVIOUS_RESULT = "reused_previous_result"
    PROMPT_CACHE_HIT = "prompt_cache_hit"
    CHART_INTENT_READY = "chart_intent_ready"
    CHART_INTENT_REUSED = "chart_intent_reused"
    CHART_REUSED = "chart_reused"
    CHART_READY = "chart_ready"
    ASSISTANT_READY = "assistant_ready"
    FINISHED = "finished"
    FAILED = "failed"
    STOPPED = "stopped"


STAGE_TO_STATUS: dict[str, AskStatus] = {
    STAGE_INTENT_CLASSIFIED: AskStatus.UNDERSTANDING,
    STAGE_SEARCHING: AskStatus.SEARCHING,
    STAGE_SEARCHING_DONE: AskStatus.SEARCHING,
    STAGE_PLANNING: AskStatus.PLANNING,
    STAGE_PLANNING_DONE: AskStatus.PLANNING,
    STAGE_GENERATING: AskStatus.GENERATING,
    STAGE_SQL_GENERATED: AskStatus.GENERATING,
    STAGE_CORRECTING: AskStatus.CORRECTING,
    STAGE_QUERY_EXECUTED: AskStatus.QUERY_EXECUTED,
    STAGE_REUSED_PREVIOUS_RESULT: AskStatus.REUSED_PREVIOUS_RESULT,
    STAGE_PROMPT_CACHE_HIT: AskStatus.PROMPT_CACHE_HIT,
    STAGE_CHART_INTENT_READY: AskStatus.CHART_INTENT_READY,
    STAGE_CHART_INTENT_REUSED: AskStatus.CHART_INTENT_REUSED,
    STAGE_CHART_REUSED: AskStatus.CHART_REUSED,
    STAGE_CHART_READY: AskStatus.CHART_READY,
    STAGE_ASSISTANT_READY: AskStatus.ASSISTANT_READY,
}


DEFAULT_STAGE_STATUS = AskStatus.GENERATING
